// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphqlblog

type Blog struct {
	ID       string `json:"id"`
	AuthorID string `json:"author_id"`
	Title    string `json:"title"`
	Content  string `json:"content"`
}

type NewBlog struct {
	AuthorID string `json:"author_id"`
	Title    string `json:"title"`
	Content  string `json:"content"`
}
